---
- name: Setup Exel Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Import exel setup variables
      include_vars: vars/exel-stack-setup

    - name: Create exel ec2 key
      ec2_key:
        name: exelkey
        region: "{{region}}"
      register: exelkey_out

    - name: Save private key into file loginkey_exel.pem
      copy:
        content: "{{exelkey_out.key.private_key}}"
        dest: "./loginkey_exel.pem"
        mode: 0600
      when: exelkey_out.changed